### PR TITLE
channel.addEventListener doesn't work on iOS and safari. Made a chang…

### PR DESCRIPTION
**Pull request by wangzhen263**
…e on this.

### CODE REVIEW

**Comment by DamonOehlman** [comment]
Cool Jeff - looks good.

@nathanoehlman you right to merge this one?

**Comment by nathanoehlman** [comment]
@wangzhen263 My only minor thought is I'm always a bit reluctant to not use `addEventListener` if it's available - would it be acceptable to check for `.addEventListener` and use that if available, otherwise default to the `on###` handlers?

**Comment by wangzhen263** [comment]
Yeah..just changed it.

**Comment by nathanoehlman** [comment]
Thanks @wangzhen263 - published as `2.0.1`

**Pull request merged**
